dataset:
  path: training/structure_dataset.json
  categories:
    - instruction
    - body
    - tile
    - ball
    - target_ball
    - bear
    - fried_chicken
    - letter
    - target_letter
    - main_letter

train:
  epochs: 15
  batch_size: 4
  lr: 0.0005
  val_split: 0.1

augmentations:
  - type: HorizontalFlip
  - type: RandomBrightnessContrast

